<img src='cover.jpg'alt="Matrix" height="full" width="full" align='left'>

In [23]:
import numpy as np 
import matplotlib.pyplot as plt

# Vectors 
 
What is Vector?
A n-dimensional vector y is an ordered collection of k real numbers y1 , y2 , . . . , yn, and is written as 
y = (y1,y2,...,yn). 

In [2]:
#vectors

y = [1,2,3,4,5,6]
y

[1, 2, 3, 4, 5, 6]

In [6]:
#using numpy
import numpy as np

x = [1,2,3,4,5,6]
y = np.array([1,2,3,4,5,6])
print(x)
print(type(x))
print(type(y))


[1, 2, 3, 4, 5, 6]
<class 'list'>
<class 'numpy.ndarray'>


# Matrices

A Matrix is defined to be a rectangular array of numbers. Whose dimension is m by n. A is called square if m = n. The numbers ai j are referred to as the elementsof A.

<img src='matrix.png' alt="Matrix" height="300" width="300" align='left'>

In [7]:
# matrices

m = np.array([[1,5,3],
             [4,7,5],
             [7,5,6]])

# preview matrix
print(m)

# view dimensions
print(m.shape)

[[1 5 3]
 [4 7 5]
 [7 5 6]]
(3, 3)


# Matrix Transpose 

<img src='trans.jpg' align='left'>



In [8]:
# matrix transpose

print('Matrix Transpose:\n',m.transpose(), '\n')

Matrix Transpose:
 [[1 4 7]
 [5 7 5]
 [3 5 6]] 



# Matrix Determinant

<img src='determinant.png' align='left'>

In [17]:
# matrix determinant

print ('Matrix Determinant:',np.linalg.det(m),'\n')

Matrix Determinant: -15.0 



# Matrix Inverse

<img src='inverse.png'align='left' >


In [19]:
# matrix inverse
m_inv = np.linalg.inv(m)
print('Matrix Inverse:\n',m_inv)

Matrix Inverse:
 [[-1.13333333  1.         -0.26666667]
 [-0.73333333  1.         -0.46666667]
 [ 1.93333333 -2.          0.86666667]]


# Identity Matrix

<img src='iden.png' align='left'>

In [20]:
# identity matrix (Original Matrix * Matrix Inverse)

iden_m = np.dot(m, m_inv)
iden_m = np.round(np.abs(iden_m), 0)

print('Product of matrix and its inverse:\n',iden_m)


Product of matrix and its inverse:
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Eigen Decompostion

Eigen means own or self. 
Eigendecomposition is the method to decompose a square matrix into its eigenvalues and eigenvectors. 
For a matrix A, if
        Av=λv
then 
v is an eigenvector of matrix A and 
λ is the corresponding eigenvalue. 
That is, if matrix A is multiplied by a vector and the result is a scaled version of the same vector, then it is an eigenvector of A and the scaling factor is its eigenvalue.



In [32]:
# eigendecomposition

m = np.array([[1,4,3],
              [4,8,2],
              [3,0,6]])

eigen_vals, eigen_vecs = np.linalg.eig(m)

print('Eigen Value:', eigen_vals, '\n')
print('Eigen Vector:\n', eigen_vecs, '\n')


Eigen Value: [ -1.53771503  10.70683037   5.83088467] 

Eigen Vector:
 [[ 0.88691954 -0.43837763 -0.04359003]
 [-0.29794271 -0.85425723 -0.63258938]
 [-0.35299273 -0.27940945  0.77325971]] 



# SVD

#####  SVD a.k.a Singular Value Decomposition is a matrix factorization method. Matrix Factorization is a representation of a matrix into a product of matrices. There are many different matrix factorization and each used for different class of problems.


<img src='SVD.png' height="full" width="full" align='left'>  <br>
A is an m × n matrix <br>
U is an m × n orthogonal matrix <br>
S is an n × n diagonal matrix <br>
V is an n × n orthogonal matrix <br>

##### The diagonal values of Σ are known as Singular values of M.
Conjugate Transpose: The conjugate transpose of a matrix interchanges the row and column index for each element.<br>
Identity matrix: It is a square matrix in which all the elements of the principal diagonal are ones and all other elements are zeros.<br>
Diagonal Matrix: It is a matrix in which the entries outside the main diagonal are all zero.<br>
Unitary matrix: Matrices whose conjugate transpose is also its inverse, that is UU*=I.<br>
Singular Values: Basically it denotes the square root of the eigenvalues of XX* where X is a matrix <br>

In [38]:
# SVD
m = np.array([[1, 3, 2],
              [4, 7, 8],
              [4, 8, 9]])

U, S, VT = np.linalg.svd(m)

print ('Getting SVD outputs:-\n')
print('U:\n', U, '\n')
print('S:\n', S, '\n')
print('VT:\n', VT, '\n')

Getting SVD outputs:-

U:
 [[-0.20851336 -0.9652919   0.15726959]
 [-0.65219648  0.25706784  0.71313104]
 [-0.72880857  0.04612668 -0.68316206]] 

S:
 [ 17.40756876   0.93974996   0.3056466 ] 

VT:
 [[-0.32931271 -0.63313747 -0.70049275]
 [ 0.26335319 -0.77402232  0.57579037]
 [ 0.90675148 -0.00513808 -0.42163416]] 



# Descriptive Statistics
Descriptive statistics uses the data to provide descriptions of the population, either through numerical calculations or graphs or tables.

In [63]:
# descriptive statistics
import scipy as sp
import numpy as np
from scipy import stats

# get data
nums = np.random.randint(1,30, size=(1,18))[0]
print('Data: ', nums)

Data:  [ 3  7 18  2  7 29 12  5 24  9 21 11 29 11 10 17 29 25]


In [64]:
# get descriptive stats
print ('Mean:', sp.mean(nums))
print ('Median:', sp.median(nums))
print ('Mode:', sp.stats.mode(nums))
print ('Standard Deviation:', sp.std(nums))
print ('Variance:', sp.var(nums))
print ('Skew:', sp.stats.skew(nums))
print ('Kurtosis:', sp.stats.kurtosis(nums))

Mean: 14.9444444444
Median: 11.5
Mode: ModeResult(mode=array([29]), count=array([3]))
Standard Deviation: 9.0090832079
Variance: 81.1635802469
Skew: 0.304707786888169
Kurtosis: -1.2789935717947152


# Natural-language processing (NLP)

A field of computer science, artificial intelligence concerned with the interactions between computers and human (natural) languages, and, in particular, concerned with programming computers to fruitfully process large natural language data.

###### NLTK has been called “a wonderful tool for teaching, and working in, computational linguistics using Python,” and “an amazing library to play with natural language.”


<img src='dialogue.png' height='500' width='600' align='left'>

In [22]:
import nltk
from nltk.corpus import treebank


sentence = """On 10th March 2018 at 2:30p I'm giving Interview in IIT Gandhinagar."""
tokens = nltk.word_tokenize(sentence)

print('Tokens: ',tokens,'\n \n' )

tagged = nltk.pos_tag(tokens)
print('Tagged: ',tagged,'\n \n')

entities = nltk.chunk.ne_chunk(tagged)
print('Tree', entities,'\n \n')

entities.draw()

t = treebank.parsed_sents('wsj_0001.mrg')[0]
t.draw()

Tokens:  ['On', '10th', 'March', '2018', 'at', '2:30p', 'I', "'m", 'giving', 'Interview', 'in', 'IIT', 'Gandhinagar', '.'] 
 

Tagged:  [('On', 'IN'), ('10th', 'CD'), ('March', 'NNP'), ('2018', 'CD'), ('at', 'IN'), ('2:30p', 'CD'), ('I', 'PRP'), ("'m", 'VBP'), ('giving', 'VBG'), ('Interview', 'NNP'), ('in', 'IN'), ('IIT', 'NNP'), ('Gandhinagar', 'NNP'), ('.', '.')] 
 

Tree (S
  On/IN
  10th/CD
  March/NNP
  2018/CD
  at/IN
  2:30p/CD
  I/PRP
  'm/VBP
  giving/VBG
  (ORGANIZATION Interview/NNP)
  in/IN
  (ORGANIZATION IIT/NNP Gandhinagar/NNP)
  ./.) 
 



<img src="out.png">